name: Node Continuoues Intergration
on:
  push:
    branches: test

jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI
        run: npm ci
      - name: 2e2
        run: npx cypress run
      - name: Build
        run: npm run build
# idk
