name: Node Continuoues Intergration
on:
  push:
    branches: [master]

jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI
        run: npm ci
      - name: Test
        run: npm test
      - name: 2e2
        run: npm run e2e
      - name: Build
        run: npm run build
# idk
