name: Node Continuoues Intergration
on:
  push:
    branches: test

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Pull Back
        run: docker pull szymonnethermind/demerzelsolutions_ndm_con:last
      - name: Docker Pull Front
        run: docker pull szymonnethermind/demerzelsolutions_ndm_front:last
      - name: Run App
        run: |
          echo "before all"
          docker-compose up
          echo "after"
          echo "before cyp"
          npx cypress run  --spec cypress/integration/myTests/**/*
      # - name: Cypress

# idk
#asdasd
