name: Node Continuoues Intergration
on:
  push:
    branches: test

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Pull
      - run: docker pull nethermind/nethermind
      - uses: actions/checkout@v2
      - name: Cypress
      - run: npx cypress run  --spec cypress/integration/myTests/**/*
# idk
