name: Node Continuoues Intergration
on:
  push:
    branches: test

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 2e2
        run: npx cypress run  --spec cypress/integration/myTests/**/*
# idk
