name: Node Continuoues Intergration
on:
  push:
    branches: test

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Pull
        run: docker pull szymonnethermind/demerzelsolutions_ndm_con
      - uses: actions/checkout@v2
      - name: Docker Run
        run: docker run szymonnethermind/demerzelsolutions_ndm_con
      - name: Cypress
        run: npx cypress run  --spec cypress/integration/myTests/**/*
# idk
